---
title: "Practical 0"
author: "Rifat Fariha"
date: "2024-05-17"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse) 
library(datasauRus)
```

```{r}
datasaurus_dozen %>%
  count(dataset)
```

```{r}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r}
dino_data %>%
  summarize(r = cor(x, y))
```
```{r}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r}
star_data %>%
  summarize(r = cor(x, y))
```

```{r}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r}
circle_data %>%
  summarize(r = cor(x, y))
```

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```